---
apiVersion: v1
kind: Service
metadata:
  name: testing3
  namespace: team1
  labels:
    app: testing3
    service: testing3
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing3